### ISSUE TITLE
Bottom-up segmentation

### ISSUE THREAD

**Issue by spono** [Jean-Romain/lidRplugins#10]
It seems that the algorithm from Shendryk is freely available:
[https://github.com/yurithefury/ForestMetrics](https://github.com/yurithefury/ForestMetrics)

I know your position on new segmentation algorithms: I don't know if this is a "simple" binding-thing like it has been for CSF, I'm simply putting here this link to show there's part of the work done, just in case :)
cheers

**Comment by Jean-Romain** [comment]
Thank you for sharing. From a R package perspective the second sentence of the readme closes the discussion. It is based on PCL so there is no way I can make it working in R 'as is'.
