### ISSUE TITLE
Install require lidR v4.0

### ISSUE THREAD

**Issue by Mandrackes-lidR** [Jean-Romain/lidRplugins#14]
Hello,

Just to say that the installation program of lidRplugins now require lidR v4.0.0 which is not out if I not wrong, maybe there is a beta. 
Can it be solved or do we need to wait the v4.0.0 to use lidRplugins ?

**Comment by Jean-Romain** [comment]
You can install v4 https://github.com/r-lidar/lidR

Official release date within 2 weeks
