### ISSUE TITLE
Hamraz2016() not working

### ISSUE THREAD

**Issue by Johanson20** [Jean-Romain/lidRplugins#15]
I recently updated my liDRplugins package in R to version 0.3.0, and when it's called with the `segment_trees()` function, it throws this error:

```
"Error: lidR::lasclipCircle is defunct. Use clip_circle instead."
```
Prior to my update, it worked fine. You can replicate this error with the documentation or help function for `hamraz2016()`:

```
LASfile <- system.file("extdata", "MixedConifer.laz", package="lidR")
las <- readLAS(LASfile, select = "xyz", filter = "-drop_z_below 0")
col <-  pastel.colors(200)

las <- segment_trees(las, hamraz2016())
```

**Comment by Jean-Romain** [comment]
Your example runs fine on my machine. I think you did not updated `lidRplugins` properly. Version numbers are meaningless for `lidRplugins`. The package is not well and actively  maintained and I do not respect versioning. So version 0.3.0 does not necessarily means you have the latest

**Comment by Johanson20** [comment]
Okay, it works now. I had to re-install the package and updated my other packages before it worked.
