### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by DijoG** [Jean-Romain/lidRplugins#18]
Dear Jean-Romain,

lidR version 4.0.2. is installed.

After executing:
> remotes::install_github("Jean-Romain/lidRplugins")

The following error message appears:
Downloading GitHub repo Jean-Romain/lidRplugins@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/Jean-Romain/lidRplugins/tarball/HEAD' failed

Could you please help me to get the plugins installed.
Thank you in advance and
best,
Gergo Dioszegi

**Comment by Jean-Romain** [comment]
Retry later. This is not supposed to happen.

**Comment by DijoG** [comment]
It does work, thank you!
It additinally requires the EBImage package.

install.packages("BiocManager") 
BiocManager::install("EBImage")
remotes::install_github("Jean-Romain/lidRplugins")
