### ISSUE TITLE
Fail to install dependencies

### ISSUE THREAD

**Issue by ErvanCH** [Jean-Romain/lidRplugins#2]
Hi Jean-Romain,

I have tried to install the plugin, but it failed. I got the following message while installing the dependencies:

package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’
package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Ervan\AppData\Local\Temp\RtmpUJJh1t\downloaded_packages
"C:/PROGRA1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Ervan/AppData/Local/Temp/RtmpUJJh1t/devtools14ec73d42cfe/Jean-Romain-lidRplugins-6ca991f"  \
  --library="C:/Users/Ervan/Documents/Work/R/R.library" --install-tests 

**ERROR: dependencies 'data.table', 'Rcpp' are not available for package 'lidRplugins'
 removing 'C:/Users/Ervan/Documents/Work/R/R.library/lidRplugins'
In R CMD INSTALL
Installation failed: Command failed (1)****

Any idea of what could cause this?
Thanks
Ervan

**Comment by Jean-Romain** [comment]
Intall packages data.table and Rcpp
