### ISSUE TITLE
lidRplugins not compatible with lidR v2.2

### ISSUE THREAD

**Issue by JakubCha** [Jean-Romain/lidRplugins#3]
Hello,

Seems like `lidRplugins` is no compatible with most recent version of `lidR`.
tree_detection algorithm gives:
 ```
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'stopif_wrong_context' not found
```
Cheers!

**Comment by Jean-Romain** [comment]
Thank you for reporting. Do not hesitate to ensure that `lidRplugins` works everytime you are update the `lidR` package. I don't use `lidRplugins` and actually at this moment it is not even installed on my computer. I never check reverse dependency (I should). I will fix that today.

**Comment by Jean-Romain** [comment]
Is it compatible with lidR 2.1.3 ?

**Comment by JakubCha** [comment]
The last version of lidR I checked that lidRplugins are compatible with (no errors) is 2.0.2.

**Comment by Jean-Romain** [comment]
If fixed this specific issue. 

However there was a lot of uncommited modification in my `lidRplugins` folder with new algorithms, algorithms removed and so on. I don't remember what was the state of the package and what is its states now. I only remember that I used it and it worked. 

So let try it. Do not hesitate to communicate if you have question.

I know that I should test this package regularly as if it was a CRAN package. But... I do not.

**Comment by felaineforever** [comment]
Dear Jean,
I am trying to use the lidRplugins to segment trees, but when I install it. I got error message:
ERROR: dependencies 'rgeos', 'EBImage', 'rgdal' are not available for package 'lidRplugins'
* removing 'D:/Program Files/R/R-devel/library/lidRplugins'
How should I deal with this problem? Thank you.
